import { defineEventHandler, setHeader, sendStream } from 'h3';
import Handlebars from 'handlebars';
import wkhtmltopdf from 'wkhtmltopdf';
import type {
	AuthorityLetter,
	FeedbackTrail,
} from '~/types/corporate-valuations/authority-letters';

export default defineEventHandler(async (event) => {
	const source = deriveSource();
	const body: AuthorityLetter = await readBody(event);

	const hbsInstance = Handlebars.create();
	hbsInstance.registerHelper('findFirstComment', (input: FeedbackTrail[] | null) => {
		if (!input || input.length == 0) return '-';

		return input[0].feedback;
	});
	const template = hbsInstance.compile(source);
	const html = template(body);

	// 2. Set Response Headers
	setHeader(event, 'Content-Type', 'application/pdf');
	setHeader(event, 'Content-Disposition', 'attachment; filename="document.pdf"');

	// 3. Generate PDF Stream
	// wkhtmltopdf returns a Node stream that we can pipe directly to the response
	const pdfStream = wkhtmltopdf(html, {
		pageSize: 'A4',
		orientation: 'Portrait',
		disableSmartShrinking: true,
	});

	// 4. Return the stream to the client
	return sendStream(event, pdfStream);
});

function deriveSource(): string {
	return `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Assessment Authorization Form</title>
    <style>
      body {
          font-family: Arial, sans-serif;
          margin: 0;
          padding: 50px;
          color: #333;
          // background-color: #f4f4f4;
      }

      .header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 20px;
      }

      .logo-container {
          display: flex;
          align-items: center;
      }

      .logo-svg {
          width: 50px;
          height: 50px;
          margin-right: 10px;
      }

      .company-name {
          font-weight: bold;
          font-size: 1.2em;
          color: #004080; /* Placeholder blue color */
      }

      .address-block {
          font-size: 0.8em;
          text-align: left;
          margin-top: 5px;
      }

      .date-container {
          font-weight: bold;
          text-align: right;
          font-size: 1em;
      }

      .title {
          text-align: center;
          font-size: 1.2em;
          font-weight: bold;
          margin-bottom: 10px;
          text-decoration: underline;
      }

      .disclaimer {
          text-align: left;
          margin-bottom: 20px;
          font-size: 1em;
      }

      .disclaimer strong {
          font-weight: bold;
      }

      .details-table {
          width: 100%;
          border-collapse: collapse;
          border-radius: 10px;
          overflow: hidden; /* Round corners effect */
          border: 4px solid #ddd;
          margin-bottom: 30px;
      }

      .details-table th, .details-table td {
          text-align: left;
          padding: 12px;
          border: none; /* No inner cell borders */
      }

      .details-table th {
          font-weight: bold;
          color: #555;
          width: 40%;
          font-size: 1.1em;
      }

      .details-table td {
          color: #000;
      }

      .details-table tbody tr:nth-child(even) {
          background-color: #f9f9f9;
      }

      .details-table tbody tr:nth-child(odd) {
          background-color: #fff;
      }

      /* Specific border styles for the table */
      .details-table tbody tr:first-child th,
      .details-table tbody tr:first-child td {
          border-top: none;
      }

      .details-table tbody tr:last-child th,
      .details-table tbody tr:last-child td {
          border-bottom: none;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="logo-container">
        <div>
          <span class="company-name">Regent Auto Valuers</span>
          <div class="address-block">
            REGENT AUTOMOBILE VALUERS AND ASSESSORS<br />
            TRV PLAZA, 2<sup>ND</sup> FLOOR RM 2B, MUTHITHI ROAD<br />
            WESTLANDS - NAIROBI<br />
            P.O BOX 34365 - 00100<br />
            <strong>Telephone:</strong> 0722608210<br />
            <strong>Email:</strong> customercare@regentautovaluers.co.ke
          </div>
        </div>
      </div>
    </div>

    <div class="title">Assessment Authorization Form</div>

    <div class="disclaimer">
      {{#if createdByBroker }}
        This authorization letter has been generated by <strong>{{ agencyName }}</strong> on behalf of <strong>{{ corpOrganization.corpName }}</strong> based on the following information:
      {{else}}
        This authorization letter has been generated by <strong>{{ corpOrganization.corpName }}</strong> based on the following information:
      {{/if}}
    </div>

    <table class="details-table">
      <thead>
      <tr>
        <th>Entry</th>
        <th>Details</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Client</td>
        <td>{{ clientName }}</td>
      </tr>
      <tr>
        <td>Phone Number</td>
        <td>{{ clientPhone }}</td>
      </tr>
      <tr>
        <td>Vehicle</td>
        <td>{{ registrationNumber }}</td>
      </tr>
      <tr>
        <td>Policy Number</td>
        <td>{{ policyNumber }}</td>
      </tr>
      <tr>
        <td>Authorized By</td>
        <td>{{ authorizedBy.username }} ({{ authorizedBy.phoneNumber }})</td>
      </tr>
      <tr>
        <td>Created On</td>
        <td>{{ createdOn }}</td>
      </tr>
      <tr>
        <td>Instructions</td>
        <td>{{ findFirstComment feedbackTrail }}</td>
      </tr>
      </tbody>
    </table>

    <div class="notes-container">
      <p style="font-weight: bold;">NOTE TO THE INSURED:</p>
      <p>Please ensure to avail the following missing at the time of valuation: <strong>Authority Letter, Certificate of Registration, National ID, KRA PIN, Vehicle Logbook</strong>.</p>
      <p>In absence of the above-mentioned documents, the assessment exercise cannot be completed. Please note that this cover will revert to Third Party only if the vehicle is not valued within 14 days of cover inception.</p>
    </div>
  </body>
</html>`;
}
