name: AVA-Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set latest run number
        id: set_run_number
        run: |
          echo "DEV_TIME_HOST=${{ secrets.DEV_TIME_HOST }}" >> .env
          echo "GOOGLE_MAPS_APIKEY=${{ secrets.GOOGLE_MAPS_APIKEY }}" >> .env
          echo "VALUATION_BASE_URL=${{ secrets.VALUATION_BASE_URL }}" >> .env
          echo "VALUATION_BASE_UNAME=${{ secrets.VALUATION_BASE_UNAME }}" >> .env
          echo "VALUATION_BASE_PASS=${{ secrets.VALUATION_BASE_PASS }}" >> .env
          echo "AVA_BASE_URL=${{ secrets.AVA_BASE_URL }}" >> .env
          echo "IMAGE_TAG=${{ github.run_number }}" >> .env


          echo "Frontend IMAGE_TAG set to: ${{ github.run_number }}"         
    
      - name: Log IMAGE_TAG from .env  
        run: |
          IMAGE_TAG=$(cat .env | grep IMAGE_TAG | cut -d '=' -f 2)
          echo "IMAGE_TAG: $IMAGE_TAG"
          cat .env
  
      - name: Build Docker image
        run: docker build --no-cache -t bensongathu/avafrontend:${{ github.run_number }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push bensongathu/avafrontend:${{ github.run_number }}

      - name: SSH into DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            export DOCKER_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}"
            export GITHUB_RUN_NUMBER="${{ github.run_number }}"
            PREVIOUS_TAG=$(($GITHUB_RUN_NUMBER - 1))
            cd /home/projects/AVA
            # Stop and remove the AvaFrontend container
            docker-compose --env-file ./regent-cui/.env -f docker-compose.yml stop AvaFrontend
            docker-compose --env-file ./regent-cui/.env -f docker-compose.yml rm -f AvaFrontend
            
            # Now attempt to remove the previous image
            docker rmi "${DOCKER_USERNAME}/avafrontend:${PREVIOUS_TAG}" || true
            
            # Proceed with the rest of the script
            docker pull "${DOCKER_USERNAME}/avafrontend:${GITHUB_RUN_NUMBER}"
            docker-compose --env-file ./regent-cui/.env -f docker-compose.yml build AvaFrontend
            docker-compose --env-file ./regent-cui/.env -f docker-compose.yml up -d AvaFrontend
          